services:
  haproxy:
    image: ghcr.io/openconext/openconext-basecontainers/haproxy28:latest
    ports:
      - 80:80
      - 443:443
    networks:
      coreconextdev:
        aliases:
          - engine.dev.openconext.local
          - engine-api.dev.openconext.local
          - profile.dev.openconext.local
          - userlifecycle.dev.openconext.local
          - manage.dev.openconext.local
          - connect.dev.openconext.local
          - voot.dev.openconext.local
          - pdp.dev.openconext.local
          - aa.dev.openconext.local
    hostname: haproxy.docker

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      coreconextdev:
    volumes:
      - ./dbschema:/docker-entrypoint-initdb.d
      - openconext_mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    hostname: mariadb.docker
    ports:
      - 3306:3306

  mongo:
    image: bitnami/mongodb:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGODB_ROOT_PASSWORD: secret
      MONGODB_REPLICA_SET_NAME: openconext
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: secretsecret
      MONGODB_ADVERTISED_HOSTNAME: mongodb
    volumes:
      - ./mongo/:/docker-entrypoint-initdb.d/
      - openconext_mongodb:/bitnami/mongodb
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "-u",
          "managerw",
          "-p",
          "secret",
          "--eval",
          "db.stats().ok",
          "mongodb://127.0.0.1/manage",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      coreconextdev:
    hostname: mongodb

  engine:
    image: ghcr.io/openconext/openconext-engineblock/engineblock:feature-docker_configs
    volumes:
      - ./:/config
      - ./engine/parameters.yml:/var/www/html/app/config/parameters.yml
    networks:
      coreconextdev:
    healthcheck:
      test: ["CMD", "curl", "--fail", "-s", "http://localhost/health"]
      timeout: 5s
      retries: 10
    hostname: engine.docker
    depends_on:
      mariadb:
        condition: service_healthy

  profile:
    image: ghcr.io/openconext/openconext-profile/profile:feature-docker_configs
    environment:
      APP_ENV: prod
    volumes:
      - ./:/config
    networks:
      coreconextdev:
    hostname: profile.docker

  mujina-idp:
    image: ghcr.io/openconext/mujina/mujina-idp:8.0.10-SNAPSHOT
    volumes:
      - ./:/config
    networks:
      coreconextdev:
    command: "--spring.config.location=/config/mujina/"
    hostname: mujina.docker

  managegui:
    image: ghcr.io/openconext/openconext-manage/manage-gui:snapshot
    environment:
      HTTPD_CSP: ""
      HTTPD_SERVERNAME: "manage.dev.openconext.local"
      OPENCONEXT_INSTANCENAME: "OpenConext dev"
      OPENCONEXT_ENGINE_LOGOUT_URL: "https://engine.dev.openconext.local/logout"
      OPENCONEXT_HELP_EMAIL: "support@openconext.org"
      SHIB_ENTITYID: "https://manage.dev.openconext.local/shibboleth"
      SHIB_REMOTE_ENTITYID: "https://engine.dev.openconext.local/authentication/idp/metadata"
      SHIB_REMOTE_METADATA: "https://engine.dev.openconext.local/authentication/idp/metadata"
    volumes:
      - ./:/config
    networks:
      coreconextdev:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: managegui.docker
    depends_on:
      engine:
        condition: service_healthy

  manage:
    image: ghcr.io/openconext/openconext-manage/manage-server:snapshot
    environment:
      USE_SYSTEM_CA_CERTS: true
    volumes:
      - ./manage/:/config/
      - ./haproxy/haproxy.crt:/certificates/haproxy.crt
    networks:
      coreconextdev:
    entrypoint: /__cacert_entrypoint.sh
    command: "java -jar app.jar --spring.profiles.active=devconf"
    hostname: manageserver.docker
    working_dir: /
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/internal/health",
        ]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 10s
    depends_on:
      mongo:
        condition: service_healthy

  oidcng:
    image: ghcr.io/openconext/openconext-oidcng/oidcng:snapshot
    networks:
      coreconextdev:
    volumes:
      - ./oidcng/:/config/
      - ./haproxy/haproxy.crt:/certificates/haproxy.crt
    entrypoint: /__cacert_entrypoint.sh
    command: "java -jar app.jar --spring.profiles.active=devconf"
    hostname: oidcng.docker
    working_dir: /
    depends_on:
      mongo:
        condition: service_healthy
    profiles:
      - "oidc"
      - "teams"
      - "extras"

  oidcplaygroundgui:
    image: ghcr.io/openconext/openconext-oidc-playground/oidc-playground-gui:snapshot
    networks:
      coreconextdev:
    hostname: oidcplagroundgui.docker
    profiles:
      - "oidc"
      - "teams"
      - "extras"

  oidcplaygroundserver:
    image: ghcr.io/openconext/openconext-oidc-playground/oidc-playground-server:snapshot
    environment:
      USE_SYSTEM_CA_CERTS: true
    volumes:
      - ./haproxy/haproxy.crt:/certificates/haproxy.crt
    networks:
      coreconextdev:
    entrypoint: /__cacert_entrypoint.sh
    command: "java -jar app.jar --spring.profiles.active=devconf"
    hostname: oidcserver.docker
    working_dir: /
    profiles:
      - "oidc"
      - "teams"
      - "extras"

  teamsgui:
    image: ghcr.io/openconext/openconext-teams-ng/teams-gui:snapshot
    volumes:
      - ./:/config
    environment:
      HTTPD_CSP: ""
      HTTPD_SERVERNAME: "teams.dev.openconext.local"
      OPENCONEXT_INSTANCENAME: "OpenConext dev"
      OPENCONEXT_ENGINE_LOGOUT_URL: "https://engine.dev.openconext.local/logout"
      OPENCONEXT_HELP_EMAIL: "support@openconext.org"
      SHIB_ENTITYID: "https://teams.dev.openconext.local/shibboleth"
      SHIB_REMOTE_ENTITYID: "https://engine.dev.openconext.local/authentication/idp/metadata"
      SHIB_REMOTE_METADATA: "https://engine.dev.openconext.local/authentication/idp/metadata"
    networks:
      coreconextdev:
    hostname: teamsgui.docker
    depends_on:
      engine:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    profiles:
      - "teams"
      - "extras"

  teamsserver:
    image: ghcr.io/openconext/openconext-teams-ng/teams-server:snapshot
    environment:
      USE_SYSTEM_CA_CERTS: true
    volumes:
      - ./haproxy/haproxy.crt:/certificates/haproxy.crt
    networks:
      coreconextdev:
    entrypoint: /__cacert_entrypoint.sh
    command: "java -jar app.jar --spring.profiles.active=devconf"
    hostname: teamsserver.docker
    working_dir: /
    profiles:
      - "teams"
      - "extras"

  voot:
    image: ghcr.io/openconext/openconext-voot/voot:snapshot
    environment:
      USE_SYSTEM_CA_CERTS: true
    networks:
      coreconextdev:
    volumes:
      - ./haproxy/haproxy.crt:/certificates/haproxy.crt
    entrypoint: /__cacert_entrypoint.sh
    command: "java -jar app.jar --spring.profiles.active=devconf"
    hostname: voot.docker
    working_dir: /
    profiles:
      - "teams"
      - "extras"

  pdpserver:
    image: ghcr.io/openconext/openconext-pdp/pdp-server:snapshot
    environment:
      USE_SYSTEM_CA_CERTS: true
    networks:
      coreconextdev:
    volumes:
      - ./haproxy/haproxy.crt:/certificates/haproxy.crt
    entrypoint: /__cacert_entrypoint.sh
    command: "java -jar app.jar --spring.profiles.active=devconf"
    hostname: pdpserver.docker
    working_dir: /
    profiles:
      - "extras"

  pdpgui:
    image: ghcr.io/openconext/openconext-pdp/pdp-gui:snapshot
    volumes:
      - ./:/config
    environment:
      HTTPD_CSP: ""
      HTTPD_SERVERNAME: "pdp.dev.openconext.local"
      OPENCONEXT_INSTANCENAME: "OpenConext dev"
      OPENCONEXT_ENGINE_LOGOUT_URL: "https://engine.dev.openconext.local/logout"
      OPENCONEXT_HELP_EMAIL: "support@openconext.org"
      SHIB_ENTITYID: "https://pdp.dev.openconext.local/shibboleth"
      SHIB_REMOTE_ENTITYID: "https://engine.dev.openconext.local/authentication/idp/metadata"
      SHIB_REMOTE_METADATA: "https://engine.dev.openconext.local/authentication/idp/metadata"
    networks:
      coreconextdev:
    hostname: pdpgui.docker
    depends_on:
      engine:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    profiles:
      - "extras"

  userlifecycle:
    image: ghcr.io/openconext/openconext-user-lifecycle/user-lifecycle:feature-docker_configs
    environment:
      APP_ENV: prod
    volumes:
      - ./:/config
    networks:
      coreconextdev:
    hostname: userlifecycle.docker
    depends_on:
      engine:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    profiles:
      - "extras"
      - "php"

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - 1080:1080
    command: "--ip 0.0.0.0 --smtp-port 25"
    networks:
      coreconextdev:
    hostname: mailcatcher.docker

networks:
  coreconextdev:
    driver: bridge

volumes:
  openconext_mariadb:
  openconext_mongodb:
