version: '3.8'

services:
  haproxy:
    image: ghcr.io/openconext/openconext-basecontainers/haproxy26:latest
    ports:
      - 80:80
      - 443:443
    networks:
      openconextdev:
        aliases:
          - ra.dev.openconext.local
          - middleware.dev.openconext.local
          - gateway.dev.openconext.local


  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      openconextdev:
    volumes:
      - ${PWD}/dbschema:/docker-entrypoint-initdb.d

  webauthn:
    image: ghcr.io/openconext/stepup-webauthn/stepup-webauthn:prod
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "mysql://webauthn_user:webauthn_secret@mariadb:3306/webauthn"
      APP_ENV: prod
    volumes:
      - /dev/log:/dev/log
      - ${PWD}/webauthn:/config
    networks:
      openconextdev:
  
  ssp: 
    image: ghcr.io/openconext/openconext-devssp/devssp:latest
    networks:
      openconextdev:
    volumes:
      - ${PWD}/ssp:/var/www/simplesaml/config/cert/

  middleware:
    image: ghcr.io/openconext/stepup-middleware/stepup-middleware:prod
    environment:
      - APP_ENV=prod
    networks:
      openconextdev:
    volumes:
      - ${PWD}/:/config
      - /dev/log:/dev/log

  gateway:
    image: ghcr.io/openconext/stepup-gateway/stepup-gateway:prod
    environment:
      - APP_ENV=prod
    networks:
      openconextdev:
    volumes:
      - ${PWD}/:/config
      - /dev/log:/dev/log
      - ${PWD}/gateway/surfnet_yubikey.yaml:/var/www/html/config/packages/surfnet_yubikey.yaml
  
  ra:
    image: ghcr.io/openconext/stepup-ra/stepup-ra:prod
    environment:
      - APP_ENV=prod
    networks:
      openconextdev:
    volumes:
      - ${PWD}/:/config
      - /dev/log:/dev/log

  selfservice:
    image: ghcr.io/openconext/stepup-selfservice/stepup-selfservice:prod
    environment:
      - APP_ENV=prod
    networks:
      openconextdev:
    volumes:
      - ${PWD}/:/config
      - /dev/log:/dev/log

  demogssp:
    image: ghcr.io/openconext/stepup-gssp-example/stepup-gssp-example:prod
    environment:
      - APP_ENV=prod
    networks:
      openconextdev:
    volumes:
      - ${PWD}/:/config
      - /dev/log:/dev/log
  
networks:
  openconextdev:
    driver: bridge

